const mongoose = require("mongoose");
const SalesSchema = new mongoose.Schema({
  invoiceNumber: String,
  saleDate: {type:String, required: [true, 'date is required field!']},
  ISODATE:{type:String, required:[true,'isodate is required']},
  saleTime:{type:String, required: [true, 'time is required field!']},
  year:{type:String},
  customer: {type: mongoose.Schema.Types.ObjectId, ref:"Customer", required: [true, 'customer is required field!']},
  isSale:{ type: Boolean, default: true },
  isTaxIncluded: { type: Boolean, default: false },
  taxRate: {type:Number , default:0},
  items: [{
    productId:{type:mongoose.Schema.Types.ObjectId, ref:"Product"},
    categoryId:{type:mongoose.Schema.Types.ObjectId, ref:"Category"},
    brandId:{type:mongoose.Schema.Types.ObjectId, ref:"Brand",default:null},
    unitId:{type:mongoose.Schema.Types.ObjectId, ref:"unit",default:null},
    baseItem:{type:String},
    unitCount:{type:Number,default:1},
    serial:{type:String},
    name: {type:String},
    ar_name:{type:String},
    quantity: {type:Number , default:1},
    unitPrice: {type:Number , default:0},
    unitCost:{type:Number , default:0},
    priceIncludeTax: {type:Boolean,default:false},
    taxRate: {type:Number , default:0},
    discountType: {type:String, enum: ['','amount', 'percent'], default: 'percent'} ,
    discountValue: {type:Number , default:0},
    discountAmount: {type:Number , default:0},
    itemSubTotal: {type:Number , default:0}, 
    itemTax: {type:Number , default:0},
    itemTotal: {type:Number , default:0}
  }],
  profit:{type:Number, default:0},
  discountType:{type:String, enum:['','amount', 'percent'], default: 'percent'} ,
  discountValue: {type:Number , default:0},
  discountAfterTax: { type: Boolean, default: true },
  discountAmount: {type:Number , default:0},
  subTotalAmount: {type:Number , default:0},
  taxAmount: {type:Number , default:0},
  totalAmount: {type:Number , default:0},
  netAmount: {type:Number , default:0},
  paidAmount: {type:Number , default:0},
  remainingAmount: {type:Number , default:0},
  paidAmount1: {type:Number , default:0},
  paidAmount2: {type:Number , default:0},
  payments: {type:Number , default:0},
  payment1:{type:String,required:[true,"select payment methode"]},
  payment2:{type:String,default:""},
status:{
    type:String,
    enum : ['paid','unpaid','partial','returned'],
    default: 'paid'
},
branch:{type:String, default:""},
saleInvoiceNumber:{type:String,default:""},
createdBy: {type: mongoose.Schema.Types.ObjectId,ref:"User"},
},{timestamps:true});
module.exports = mongoose.model('Sale',SalesSchema,)